resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
  - sops-config.yaml
  - argocd-service-acc.yaml
  - argocd-ingress.yaml

patches:
  - path: argocd-cm.patch.yaml
  - path: argocd-repo-server.yaml

namespace: argocd
