apiVersion: v1
kind: ConfigMap
metadata:
  name: sops-config
  namespace: argocd
data:
  .sops.yaml: |
    creation_rules:
    key_groups:
      - kms:
          - arn:aws:kms:us-east-1:767397915565:key/cec7485f-1425-46f4-8923-b148599714bb
