# apiVersion: kustomize.config.k8s.io/v1beta1
# kind: Kustomization
# resources:
#   - ../../base

# patches:
#   - path: ./auth/auth-deployment-patch.yaml
#     target:
#       kind: Deployment
#       name: auth-deployment
#   - path: ./payment/payment-deployment-patch.yaml
#     target:
#       kind: Deployment
#       name: payment-deployment