apiVersion: ENC[AES256_GCM,data:FyA=,iv:w346V92m7aW8u8z2kEDbGzrKOOQQFT80StlAlR2fglc=,tag:r9ijfGYk7bIOqu9E0s6lTw==,type:str]
kind: ENC[AES256_GCM,data:PLi2nYZ4,iv:zzryfQHXgJaMqpITHWHHFNimLOZxaqoSObMnurUCPqE=,tag:oT2+R3rZJG6ZOiPMo8I8+w==,type:str]
metadata:
    name: ENC[AES256_GCM,data:XUrIpMEaS26UVDx6,iv:2PDAsV48An183w4f6XUuvNz5iSzWDSjSyMzfTs3AagY=,tag:kDVY5Gnqg0enLL5YnQ/pGg==,type:str]
    namespace: ENC[AES256_GCM,data:kzpxR8sgHqOQdWkZ,iv:8zk2JhVrhG5aC+zMkJHg7cFXGet8ueIoRQlBt2DcODQ=,tag:yQviGzH18beaq95HqKLWPg==,type:str]
type: ENC[AES256_GCM,data:adW9G1Uk,iv:rxtlJRwgdnE4+Dm9KoF8D45CuGR9oRk9+inr05rrrTk=,tag:uDKfiwuB/xGhQHNZGFJf1A==,type:str]
data:
    DB_USER: ENC[AES256_GCM,data:0+Fbfg==,iv:Slx5PaVWHA9oAFMDC0Evrrt6VDnZqoRBZnu7o+yAbSU=,tag:L5pLV2XIPlkMesSVZgbS9g==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:wzJoTA==,iv:oPHPSdPbsi/mO3V7h2Na/rlqIR9rIufZ8PIZmd8bTVc=,tag:mMAAgcPAdmPe3WhJ+8n49g==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:<Account ID>:key/cec7485f-1425-46f4-8923-b148599714bb
          created_at: "2025-07-25T10:10:55Z"
          enc: AQICAHikekyPzKlYE3WkY54Z2bAwD954ZUUTV8KPxZAiHvdnrwHwuNJT/SzPJEMgvhvLFmcjAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMSaz98TymkD78/LnkAgEQgDvHYEuii6PHcC0FF3CUYF2/58RFCWn7rRGRA221CS8qga+IKbTgaUY8v28EknaCsEzM2W9CH8GOePmbhQ==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-07-25T10:10:56Z"
    mac: ENC[AES256_GCM,data:scDbPUvKFuGbM4YMWFIlql9w9OE6ihR7uLDY0dNEgTUP5B5hhMTFY6MOa2NoQtBPunfTo7Jo+f17jNguOrQiez4HtadLXIEmMLnqEgeK2nItr9sWqFz7zlAjYsfUZx2rQViHscWAr4hJM4jU9ulmPjVmqJcVyAw60qimujZ+5Ys=,iv:QdB2z3rZvUpX5TBrHADBaBwKP0ZGM5Q2LYSEWk6ZAp4=,tag:lO4vBNyQ7bw9kckQ0+vCDQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
