apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-volume
  namespace: microservice
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /data/database
    type: DirectoryOrCreate
