apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-claim
  namespace: microservice
spec:
  volumeName: pvc-volume
  resources:
    requests:
      storage: 2Gi
  storageClassName: standard
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
