apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-deployment
  namespace: microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-microservice
  template:
    metadata:
      labels:
        app: payment-microservice
    spec:
      containers:
        - name: payment-container
          image: nginx:latest
          ports:
            - containerPort: 3001
          volumeMounts:
            - name: auth-volume
              mountPath: /app/temp
      volumes:
        - name: auth-volume
          emptyDir: {} 
