# Database configuration
MYSQL_HOST=database-service.microservice.svc.cluster.local
MYSQL_PORT=3306
MYSQL_DATABASE=mysql1.0
DB_PASSWORD=pass
# MYSQL_USER=auth_user
# MYSQL_PASSWORD=your_secure_password

# JWT configuration
# JWT_SECRET=your_jwt_secret
# JWT_EXPIRATION_MS=3600000

# # Redis (if used for sessions or caching)
# REDIS_HOST=redis.default.svc.cluster.local
# REDIS_PORT=6379

# # Auth service internal config
# AUTH_SERVICE_PORT=8080
# AUTH_SERVICE_LOG_LEVEL=INFO
