apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - pairs: 
     env: dev 
    includeSelectors: false
    includeTemplates: true

resources:
  - ../../../base/payment

configMapGenerator:
  - name: dev-envs
    envs:
      - ./dev.properties

# generators:
#   - payment-secrets-generator.yaml

patches:
  - path: payment-deployment-patch.yaml