apiVersion: ENC[AES256_GCM,data:6Oc=,iv:G1uxXtYBw6mlrVIoHJ9xryHd0MZvDRD2q1uuy5ojcTY=,tag:+wD7v6bFfO03UXFh6oJUpQ==,type:str]
kind: ENC[AES256_GCM,data:Sq7ce1lr,iv:2dR7uLryMCG6SsAJ8ANFjTTdq+zq+prc1wLsNRyxRsw=,tag:9ErQXMhNN/7yEo/cMqJnzQ==,type:str]
metaddata:
    name: ENC[AES256_GCM,data:vtgVCR/pLn0b0L9OPPo6,iv:tjQ2CAtZlWqB6r0kepUm0+K+mQXDJ9QzaOXpt+5hnFM=,tag:8sPV5jIvfE5gyH7TMfpo4A==,type:str]
    namespace: ENC[AES256_GCM,data:xOYqbEf3MJBs2Vju,iv:jEKGByMEefIJgpZKr7qbXM5rIOF+TdEQak0b26xigbc=,tag:bW6iZN27LsZ+C+k4wZ7oxg==,type:str]
type: ENC[AES256_GCM,data:k/1JnX7J,iv:ljI7txAAnNixFJesFpo9qiXSJyrglkLxps6xQgB6dOs=,tag:tC/bJHvTdT0H1Sa5f/SOVQ==,type:str]
data:
    DB_USER: ENC[AES256_GCM,data:PDeBPA==,iv:YKxUUsXsRaVL/7eesIQNmucBFi4pZ9BcEX4PP215p84=,tag:+6GvGwtaZbcfE3IQ3embmQ==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:qwQeBw==,iv:m9CbytpJhoJMhOAiEeXA99p63sb02mNjQkcRVGZzvzM=,tag:NoT4NhDsF5EpRC06V3OYcQ==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:<Account ID>:key/cec7485f-1425-46f4-8923-b148599714bb
          created_at: "2025-07-25T10:11:19Z"
          enc: AQICAHikekyPzKlYE3WkY54Z2bAwD954ZUUTV8KPxZAiHvdnrwE3s8gWuavnoYE8o3bdtyiIAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMRgAnnzz1Ba09kK6UAgEQgDvXzrNzgVSh6TWSxkOwOtiTzrG4OTbQQQ3ZWLDJ4yt9DSRH8Bb9dC5JR3XRLjB3RJSEJMlxBQKX/082OA==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-07-25T10:11:19Z"
    mac: ENC[AES256_GCM,data:kd8ppze59spQ37sI1MCyLWkEYxsX6g1iCkAYrV0egRepKE4bMUlLLnCCekhnqWuMn7cvTvzRPy00w0sOsUOw5cOKvB71kZ5QX3JCI3bFYA7RrmBHGwp5dH7I5Jwyj7fZw+HKFJ6c2wMfbFl5FQ5Jt4t2jvPomnimrFZdJ0ibhcU=,iv:CUxbczSt91b/1PKck7jevHpWmCZpdMPoCafB8yzsumA=,tag:XOscyltgzMGCn7nTokUKEQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
