apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-deployment
  namespace: microservice
spec:
  template:
    spec:
      serviceAccountName: ecr-reader
      containers:
        - name: payment-container
          image: <Account ID>.dkr.ecr.us-east-1.amazonaws.com/payment-service:latest
          ports:
            - containerPort: 3001
          envFrom:
            - configMapRef:
                name: dev-envs-h94c8gd2bt